- name: Ensure requirements are installed (ansible needs docker-sdk for python)
  block:
    - name: Python pip
      package:
        name: python3-pip
        state: present
    - name: Docker-sdk for python
      pip:
        name:
          - docker
          - docker-compose
        state: present