services:
  mysql:
    restart: always
    networks:
      - cloud-storage
    hostname: mysql
    ports:
      - 3306:3306 # we must not expose this port in production
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:?}
      MYSQL_USER: ${MYSQL_USERNAME:?}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
      MYSQL_DATABASE: 'cloud_storage'
    volumes:
      - cs-mysql-internal-volume:/var/lib/mysql
      - cs-mysql-volume:/cloud-storage/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - cloud-storage
    ports:
      - 8080:80
    hostname: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
volumes:
  cs-mysql-internal-volume:
    external: true
  cs-mysql-volume:
    external: true
networks:
  cloud-storage:
    name: cloud-storage
    external: true