- name: Create directory tree on host
  file:
    path: /cloud-storage/mysql/internal
    state: directory

- name: Create mysql cloud-storage volume"
  community.docker.docker_volume:
    volume_name: cs-mysql-volume
    driver: local
    driver_options:
      type: none
      device: /cloud-storage/mysql
      o: bind

- name: Create mysql internal volume"
  community.docker.docker_volume:
    volume_name: cs-mysql-internal-volume
    driver: local
    driver_options:
      type: none
      device: /cloud-storage/mysql/internal
      o: bind