networks:
  cloud-storage:
    name: cloud-storage
    external: true
services:
  clientEndpoint:
    image: registry.gitlab.com/sthommet/cloud-storage/client-ep:latest
    pull_policy: always
    restart: always
    networks:
      - cloud-storage
    ports:
      - 8008:8008
    hostname: clientEndpoint
    volumes:
      - /cloud-storage/conf:/cloud-storage/conf
    environment:
      - MYSQL_CONF_PATH=/cloud-storage/conf/mysql.yaml
      - SERVER_CONF_PATH=/cloud-storage/conf/server.yaml
  diskManager:
    image: registry.gitlab.com/sthommet/cloud-storage/disk-manager:latest
    pull_policy: always
    restart: always
    networks:
      - cloud-storage
    hostname: diskManager
    volumes:
      - /cloud-storage/conf:/cloud-storage/conf
      - /cloud-storage/disk:/cloud-storage/disk
    environment:
      - MYSQL_CONF_PATH=/cloud-storage/conf/mysql.yaml
      - FS_STORAGE_PATH=/cloud-storage/disk
      - FS_CONF_FILE_NAME=disk-info.conf